######################## default configuration ####################
baseURL = "https://kelvinaerospacelab.github.io"
title = "Kelvin Aerospace Lab"
theme = "port-hugo"

############################# Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
[[params.plugins.css]]
link = "https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
[[params.plugins.css]]
link = "https://cdnjs.cloudflare.com/ajax/libs/hover.css/2.1.0/css/hover-min.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Rubik:300,400,500,700,900&display=swap"
[[params.plugins.css]]
link = "plugins/text-animation/text-animation.css"
[[params.plugins.css]]
link = "plugins/hugrid/hugrid.css"

# JS Plugins
[[params.plugins.js]]
link = "https://code.jquery.com/jquery-3.5.1.min.js"
[[params.plugins.js]]
link = "https://cdnjs.cloudflare.com/ajax/libs/waypoints/4.0.1/jquery.waypoints.js"
[[params.plugins.js]]
link = "plugins/text-animation/text-animation.js"
[[params.plugins.js]]
link = "plugins/hugrid/hugrid.min.js"


############################## navigation ###############################

# main menu
[[menu.main]]
name = "Home"
URL = "/#about"
weight = 1

[[menu.main]]
name = "About Us"
URL = "/intro/"
weight = 2

[[menu.main]]
name = "Updates"
URL = "/updates/"
weight = 3

[[menu.main]]
name = "Meetings"
URL = "/meetings/"
weight = 4

[[menu.main]]
name = "Documents"
URL = "https://docs.kelvinaero.org"
weight = 5

#################### default parameters ################################
[params]
# Meta data
description = "Kelvin Aerospace Lab (KAL) provides hands-on engineering experience in designing, building, and testing aerospace systems, sparking curiosity about space exploration and engineering while offering opportunities to learn advanced physics, engineering, and electronics in a collaborative environment."
author = "Felex"
copyright = "&copy; 2025 Kelvin Aerospace Lab. All rights reserved."
# Default OpenGraph image
defaultImage = "/images/klvweb.png"

# Logo configuration

logo_light = "images/logo.svg"
logo_dark = "images/logo-dark.svg"  # Dark mode logo
favicon = "/images/favicon1.png"

google_analytics = "G-ABCDEFG123"

# Preloader
[params.preloader]
enable = true
preloader = "images/preloader.gif" # use jpg, png, svg or gif format.

############################# social site ########################

[[params.social]]
icon = "fab fa-github"
link = "https://github.com/kelvinaerospacelab"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:kelvinaero@proton.me"

[[params.social]]
icon = "fab fa-google-classroom"
link = ""


contentDir = "content/english"
weight = 1
home = "Home"

